name: GitHub Metrics New

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta diariamente a medianoche UTC
  workflow_dispatch:     # Permite ejecutar manualmente
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ssanchezhlg
          base: header, metadata, activities, community, repositories, stars
          config_timezone: America/Havana
          config_output: svg
          plugin_languages: yes
          plugin_languages_threshold: 0%
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_trophies: yes
          plugin_trophies_threshold: C
          plugin_trophies_only: true
          plugin_wakatime: no  # Desactivado por defecto (requiere API key separada)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          theme: dracula

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}