name: GitHub Metrics
on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ssanchezhlg
          
          # Sin header
          #base: header, metadata, activities
          base: ""
          config_timezone: America/Havana
          
          # Debug (puedes quitarlo después)
          debug: yes
          plugins_errors_fatal: no
          
          # Lenguajes
          plugin_languages: yes
          plugin_languages_threshold: 0%
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_colors: github
          
          # Calendario
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Líneas de código
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          
          # Hábitos (CORREGIDO)
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_days: 30
          plugin_habits_from: 500
          plugin_habits_trim: yes
          
          # Logros (CORREGIDO - ignora Projects)
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_achievements_ignored: automator, infographile
          
          # Salida
          output_action: commit
          committer_branch: output
          committer_message: "chore: update metrics"